# Generated by Django 3.1.5 on 2021-01-04 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cityapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='melriverModel',
            new_name='bookModel',
        ),
    ]
